# Generated by Django 5.1.4 on 2025-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=170)),
                ('website', models.URLField(blank=True, null=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
